sudo: false
dist: trusty

language: cpp
compiler:
  - clang

git:
  depth: 1000

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:kzemek/boost'
    packages:
      - g++-6
      - libboost1.58-dev
      - libboost-filesystem1.58-dev
      - libboost-iostreams1.58-dev
      - libboost-program-options1.58-dev
      - libboost-regex1.58-dev
      - libboost-system1.58-dev
      - libboost-thread1.58-dev
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev

services:
  - mysql

cache: ccache

env:
  - BRANCH=master
  - BRANCH=multivendor_master
  - BRANCH=playeritemgossip_master
  - BRANCH=dressnpcs_master
  - BRANCH=objscale_master
  - BRANCH=gomove_master

after_success:
  - git push https://${GITHUB_TOKEN}@github.com/Rochet2/TrinityCore.git HEAD:${BRANCH} >/dev/null 2>&1

before_install:
  - export CXX="ccache clang++"
  - export CC="ccache clang"
  - export CCACHE_CPP2="true"
  - which g++ gcc clang clang++ cc c++
  - ccache --show-stats
  - git clone --depth=100 --branch=${BRANCH} https://github.com/Rochet2/TrinityCore.git server
  - cd server
  - git status
  - git remote add Trinity https://github.com/TrinityCore/TrinityCore.git
  - git fetch --depth=100 Trinity master
  - git merge -m "Merge TrinityCore master to ${BRANCH} [skip ci]" Trinity/master
  - git submodule update --init --recursive
  - git status
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mysql -uroot -e 'create database test_mysql;'
  - mkdir bin
  - cd bin
  - cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=0 -DUSE_SCRIPTPCH=0 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..
  - chmod +x contrib/check_updates.sh

script:
  - $CXX --version
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -utrinity -ptrinity auth < sql/base/auth_database.sql
  - ./contrib/check_updates.sh auth master auth localhost
  - mysql -utrinity -ptrinity characters < sql/base/characters_database.sql
  - ./contrib/check_updates.sh characters master characters localhost
  - mysql -utrinity -ptrinity world < sql/base/dev/world_database.sql
  - mysql -utrinity -ptrinity hotfixes < sql/base/dev/hotfixes_database.sql
  - cat sql/updates/world/master/*.sql | mysql -utrinity -ptrinity world
  - cat sql/updates/hotfixes/master/*.sql | mysql -utrinity -ptrinity hotfixes

  - cat sql/custom/auth/*.sql | mysql -utrinity -ptrinity auth	
  - cat sql/custom/characters/*.sql | mysql -utrinity -ptrinity characters	
  - cat sql/custom/world/*.sql | mysql -utrinity -ptrinity world
  - cat sql/custom/hotfixes/*.sql | mysql -utrinity -ptrinity hotfixes

  - mysql -uroot < sql/create/drop_mysql.sql
  - cd bin
  - make -j 4 -k && make install
  - cd check_install/bin
  - ./bnetserver --version
  - ./worldserver --version
